import type { Metadata } from "next";
import { Quicksand, Cinzel } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({ subsets: ["latin"] });
const cinzel = Cinzel({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Le Croissant",
  description: "Generated by Blackone",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} ${cinzel.className}`}>
        {children}
      </body>
    </html>
  );
}
